### ISSUE TITLE
There are problems with frame drops in 1.0.0-beta.

### ISSUE THREAD

**Issue by LazyvVv** [zzxzzk115/GoldMiner-Rebirth#4]
Maybe it's the problem of tick.lua.

**Comment by zsw-test** [comment]
unbelievable! mr.jack

**Comment by zzxzzk115** [comment]
> unbelievable! mr.jack

doge.

**Comment by zzxzzk115** [comment]
After using push.lua,  there is no longer any problems with frame drops.
